name: Format check
on: [pull_request]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          cache: "npm"
      - name: "Checking 2lab project" 
        working-directory: laba_2
        run: npm ci && npm run format && npm run lint && npm run slint